### ISSUE TITLE
Allow user to kill a job and to remove all trace of it.

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.server#10]
```
Allow user to kill a job and to remove all trace of it from the GUI. This is already
available from the command line - so most of the code is there.
```

Original issue reported on code.google.com by `dr.s.m.fisher` on 2013-05-15 12:51:26

**Comment by brianritchie1312** [comment]
Closing this as I believe it has been possible for a while. (A running job has to be Cancelled before it can be Deleted.) Note that if the job had created any output datasets/datafiles in ICAT, or any provenance records, these will not be deleted; but the IJP itself will no longer list the job.
