### ISSUE TITLE
Need to ensure that sessions do not expire

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.server#14]
```
Sessions for incomplete jobs can be refreshed easily - for interactive jobs some other
mechanism will be needed - e.g. make the job do it.

Currently sessions have been set to last for 24 hours - once this bug is fixed the
period should go back to the normal two hours.

```

Original issue reported on code.google.com by `dr.s.m.fisher` on 2013-05-15 20:08:17

**Comment by brianritchie1312** [comment]
In all current IJP instances, the session lifetime is the default (120 minutes). We have yet to encounter any problems with session expiry in practice; but it is still possible.

**Comment by brianritchie1312** [comment]
Latest commit fixes the batch case of this issue. Still to consider a solution for interactive jobs.

**Comment by brianritchie1312** [comment]
I am closing this as the case for which it was kept open (interactive jobs) is no longer relevant.
