### ISSUE TITLE
job.sh needed job name quoted

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.server#30]
```
The line in job.sh that echoes the date followed by the job name (from the drop down
list in the portal) needs to have the job name quoted so that it is possible to put
characters such as round brackets in the job names. Otherwise the job fails immediately
when your remote desktop session starts leaving you with a blank screen and no idea
what happened.

```

Original issue reported on code.google.com by `kevin.phipps13` on 2014-03-19 14:36:04

**Comment by brianritchie1312** [comment]
This probably needs to be fixed separately in each batch connector. My notes suggest that it may have been done for r92 and unixbatch already; and that I changed lsfbatch so that spaces in job names are replaced by underscores, but that is probably not enough. Will have to look again.

**Comment by brianritchie1312** [comment]
The job name that is defined in the jobtype is not supplied from the server to the batch connectors, so its syntax no longer matters. The lsfbatch connector does generate a Job Name for the bsub command, but that is constructed from the executable (from the jobtype), with whitespace replaced by underscores.

Each batch connector escapes its parameters as appropriate; however, the executable is passed verbatim to the command line in the constructed batch script; so it is a requirement that the executable defined in the job type should make sense on a command line; this seems reasonable.

I think this issue can be closed, either as "no longer relevant" or as "already fixed".
