### ISSUE TITLE
Improve job status display for users

### ISSUE THREAD

**Issue by fisherab** [icatproject/ijp.server#6]
```
Need to remove uninteresting columns, add the job time, and ensure that job ids are
simpler. If we assume that we only have one submission machine then we only need the
integer otherwise at least omit the domain name.
```

Original issue reported on code.google.com by `dr.s.m.fisher` on 2013-05-15 12:45:01

**Comment by brianritchie1312** [comment]
I think this old issue can be closed, though the definition of "uninteresting columns" may change. Job IDs are (only) integers at present.
